### ISSUE TITLE
Possible to support more DropDownStyle in ComboBox?

### ISSUE THREAD

**Issue by KyleChen9999** [dennismagno/metroframework-modern-ui#103]
Hi Dennis,

First thank you for your work which brings mordern UI for old WinForms application.
I have noticed you've fixed the drawingItem issue in ComboBox which is good. Is there any chance you can work on ComboBox control to enable the option "DropDown", "DropDownSimple" for DropDownStyle as well? I know the original code forces ComboBox to use "DropDownList" only because seems no way or too difficult to style the embed Text Box... I checked the code and have no clue how to do it at all. If you can help, it'll be much appreciated!

Kyle

**Comment by KyleChen9999** [comment]
It's already there. Please ignore this.

**Comment by JLuboff** [comment]
@KyleChen9999  How were you able to implement this? I have tried programmically
```
combobox.DropDownStyle = ComboBoxStyle.DropDown
```
But it has not affect... and I don't see it in the properties list (GUI)
