### ISSUE TITLE
ComboBox.DropDownStyle does nothing

### ISSUE THREAD

**Issue by JLuboff** [dennismagno/metroframework-modern-ui#116]
I'm trying to change the combobox drop down style to DropDown instead of DropDownList but I have tried programmically
```
combobox.DropDownStyle = ComboBoxStyle.DropDown
```
But it has not affect... and I don't see it in the properties list (GUI)

**Comment by dennismagno** [comment]
I think the dropdown style have some issue that is why it was not yet supported when using MetroStyle.

**Comment by JLuboff** [comment]
Thanks for the reply @dennismagno . So did this PR merge 9f3f364  not actually do anything?
