### ISSUE TITLE
Transparent/see-through panel with Light theme

### ISSUE THREAD

**Issue by Alexlander** [dennismagno/metroframework-modern-ui#24]
I'm able to create a see-through application, but only with the dark theme.

I've set the TransparencyKey on Transparent, the theme on Dark and the panel BackColor on Transparent.

When I set the theme on Light, most of the application goes transparent and I can't click/move it. 

Is there an sophisticated solution for using the light theme?

Right now it looks like this 
![zknnjp](https://cloud.githubusercontent.com/assets/11189629/23258973/0ff1dcec-f9cb-11e6-85b6-881973c07285.jpg)

**Comment by dennismagno** [comment]
I have tried it onlight and seems working well.  Maybe because of the color that you selected for transparency key.  I used RGB 224, 224, 224
![sample-light](https://cloud.githubusercontent.com/assets/5070675/23308814/5c642194-fae7-11e6-90c6-d6bf66ee11fb.JPG)

**Comment by Alexlander** [comment]
Ah nice! I was able to have the transparent panel without that grey filter, hope I can have that on the light theme to, then it'd be perfect

**Comment by Alexlander** [comment]
Only problem right now is that with a flat shadow like you have, that the transparent panel is grey-ish, without a shadow it's gone but I'd like to have a shadow to have contrast on a white surface. Any solution for this?

**Comment by Alexlander** [comment]
So I just removed the shadow and used FixedSingle as BorderStyle, looking good!
