### ISSUE TITLE
Update Nuget to latest GitHub Version

### ISSUE THREAD

**Issue by Spegeli** [dennismagno/metroframework-modern-ui#25]
Possible to Update Nuget to the current GitHub Version?

Last Nuget Update is from "2016-07-19" which seems a little old.

Thx

**Comment by dennismagno** [comment]
Hi,

I will try to compile this weekend.

Dennis Icasiano Magno

Website : DenRic Denise <https://denricdenise.info>
Youtube Channel : DenRic Denise - INFO
<http://www.youtube.com/subscription_center?add_user=brienne>
E-Mail : dimagnoph@gmail.com

**Comment by Spegeli** [comment]
Would be very nice ;-)

**Comment by Spegeli** [comment]
Any news when you Update the NuGet Version?

**Comment by Spegeli** [comment]
Because i made now my own .dlls i close this ticket...
