### ISSUE TITLE
Unable to show form in full screen mode.

### ISSUE THREAD

**Issue by indiepay-alundgren** [dennismagno/metroframework-modern-ui#7]
I'm using this for a video game. It looks great in windowed mode, but I need to also be able to use it in full screen (no taskbar visible, no max/min/close buttons, no titlebare, etc.). With native WinForms this works fine, but I don't see how to achieve it with Metro UI. 

Thank you!

**Comment by dennismagno** [comment]
You can add this on your Shown event

```
this.ControlBox = false;
this.FormBorderStyle = FormBorderStyle.None;
this.WindowState = FormWindowState.Normal;
this.Bounds = Screen.PrimaryScreen.Bounds; 
````
