### ISSUE TITLE
Panel with Problems!

### ISSUE THREAD

**Issue by DBenS** [dennismagno/metroframework-modern-ui#9]
Hi,

After the last change in PANEL, if we try to scroll it vertical or horizontal we got the error:

NULL REFERENCE at lines:
290 = HorizontalScrolled(this,e) and 
298 = VerticalScrolled(this,e)

and the arrows disapeared (due to AutoScroll?).

Thanks.

**Comment by dennismagno** [comment]
Fix with Commit e98c53e9
