### ISSUE TITLE
MetroTextBox does not change UseSystemPasswordChar in runtime

### ISSUE THREAD

**Issue by vandermjr** [dennismagno/metroframework-modern-ui#96]
`
//System Runtime

//Not work
If(MetroTextBox1.UseSystemPasswordChar == true) MetroTextBox1.UseSystemPasswordChar = false;

//Work
If(TextBox1.UseSystemPasswordChar == true) TextBox1.UseSystemPasswordChar = false;`

**Comment by VBHPS** [comment]
Try - 
In form load add

metroCheckBox1.Checked = true;
metroCheckBox1.Text = "Show Password";

then add to metroCheckBox1_CheckedChanged

if (metroCheckBox1.Checked == true) metroTextBox1.UseSystemPasswordChar = true;
else if (metroCheckBox1.Checked == false) metroTextBox1.UseSystemPasswordChar = false;

**Comment by vandermjr** [comment]
@VBHPS very good, solved. Thank you.
